% TWINWAVEMAKER
%
%   Reference: M. Paprota. 2023. A twin wavemaker model for liquid sloshing in a rectangular tank. Ocean Engineering, 272, 113919
%   Functions:
%   dispersionRelation       - calculates wave number based on linear dispertion relationship
%   freeSurfaceElevation     - calculates free-surface elevation based on amplitudes and eigenvalues of cosine expansion
%   paddleMotionRegular      - calculates piston-type paddle motion according to a linear transfer function with raised cosine ramp applied to the first few wave periods
%   tankCoords               - defines coordinates of a patch object according to vertices and faces of a tank
%   twinWavemakerAnalytical  - analytical solution to linear sloshing in a closed tank of constant depth generated by twin piston-type wavemakers moving according to \chi = \chi_hat*\sin(\sigma t)
%   twinWavemakerAnalyticalF - analytical solution to linear sloshing in a closed tank of constant depth generated by twin piston-type wavemakers moving according to \chi = \chi_hat*\sin(\sigma t) Faltinsen (1978) version
%   twinWavemakerEulerMod    - semi-analytical solution to linear sloshing in a closed tank of constant depth generated by twin piston-type wavemakers moving according to \chi
%   velocityComponents       - calculates component velocities as spatial derivatives of potential function based on velocity of a paddle(s) and amplitudes and eigenvalues of cosine expansion.
%   wavemakerAnalytical      - analytical solution to linear mechanically-generated gravity waves in a closed wave flume of constant depth generated by a piston-type wavemaker moving according to \chi = \chi_hat*\sin(\sigma t) and reflected at a vertical wall
%   wavemakerEulerMod        - semi-analytical solution to linear mechanically-generated gravity waves in a closed wave flume of constant depth generated by a piston-type wavemaker moving according to \chi and reflected at a vertical wall
% 
%   Scripts:
%   compAnNumTwinWavemaker   - Comparison of analytical and numerical solution to linear twin wavemaker problem
%   compAnNumWavemaker       - Comparison of analytical and numerical solution to linear wavemaker problem
%   compAnTwinWavemakerF     - Comparison of twin wavemaker problem solution and Faltinsen (1978) solution to sloshing
%   plotTwinWavemaker        - Plotting linear sloshing in a 2D tank
%   plotTwinWavemaker3D      - Plotting linear sloshing in a 3D tank
%   plotWavemaker            - Plotting mechanically generated waves in a 2D wave flume
