function [lambda, eta_hat, phi_hat] = ...
    twinWavemakerAnalytical(l,d,chi_hat,sigma,t,K,g)
% analytical solution to linear sloshing in a closed tank of constant depth generated by twin piston-type wavemakers moving according to \chi = \chi_hat*\sin(\sigma t).
%
% Input data:
% l - wave flume length (m)
% d - water depth (m)
% chi_hat - wavemaker paddle motion amplitude (m)
% sigma - wavemaker paddle motion frequency (rad/s)
% t - time domain vector (s)
% K - number of solution eigenvalues
% g - gravitational acceleration (m/s^2)
%
% Output data:
% lambda - solution eigenvalues (rad/m)
% eta_hat - free-surface amplitudes (m)
% phi_hat - velocity potential amplitudes (m^2/s)
%
% Author: Maciej Paprota
% Reference: M. Paprota. 2023. A twin wavemaker model for liquid sloshing in a rectangular tank. Ocean Engineering, 272, 113919

lambda = (2*(1:K)-1)*pi/l; % solution eigenvalues (rad/m)
omega = sqrt(g*lambda.*tanh(lambda*d)); % solution frequences (rad/s)
alpha = -4*chi_hat*sigma^2*tanh(lambda*d)./lambda/l;
eta_hat = (sin(t*sigma)-sin(t*omega).*omega/sigma).*alpha./(omega.^2-sigma^2); % eq. (28)
phi_hat = (cos(t*sigma)*sigma^2-cos(t*omega).*omega.^2).*... % eq. (29)
    alpha*g/sigma./(omega.^2-sigma^2)./omega.^2;
eta_hat(:,omega==sigma) = -(sigma*cos(t*sigma).*t+sin(t*sigma))*...
    alpha(omega==sigma)/2/sigma^2; % resonance eq. (28)
phi_hat(:,omega==sigma) = (sin(t*sigma).*t*sigma-2*cos(t*sigma))*...
    alpha(omega==sigma)*g/2/sigma^3; % resonance eq. (29)
end
